services:
  backend:
    image: backend-image
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      no_cache: true
    ports:
      - "8080:8080"
  frontend:
    image: frontend-image
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      no_cache: true
    ports:
      - "5173:5173"